spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: note-service

  # Postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/cinderdb
    driver-class-name: org.postgresql.Driver
    username: faizagha
    password: ""

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  # Flyway — top-level, sibling of jpa
  flyway:
    enabled: true

server:
  port: 8080

cinder:
  cors:
    allowed-origins: http://localhost:8000

logging:
  level:
    root: INFO
    dev.cinder: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
